[tools]
"go:golang.org/x/tools/cmd/goimports" = "0.30.0"
"go:golang.org/x/tools/gopls" = "0.18.1"
golangci-lint = "1.64.6"
lua-language-server = "latest"
shellcheck = "0.10.0"
shfmt = "3.10.0"
stylua = "2.0.2"

[env]
NVIM_APPNAME = "nvimdots.dev"
