return function()
  require("nvim-treesitter.configs").setup({
    highlight = {
      enable = true,
    },
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "html",
      "javascript",
      "json",
      "julia",
      "kconfig",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "perl",
      "python",
      "query",
      "rust",
      "svelte",
      "typescript",
      "vhs",
      "vim",
      "vimdoc",
      "vue",
      "yaml",
    },
  })
end
